### ISSUE TITLE
Feedback zu ilicop Rest PI V1

### ISSUE THREAD

**Issue by mauralp** [GeoWerkstatt/interlis-check-service#124]
Hoi Oli,
Danke erst einmal für diese Leistung! Die Response der IliValidator ist sehr schnell! :)

Einige Aspekte können vielleicht helfen, diese Applikation zu optimieren: 
1.	Der Name der Logdatei: Ilivalidator_output_.... kann durch Ilivalidator_output_error_..... ersetzt werden. 

2.     Die Log-Datei kann besser strukturiert werden und z.B. in deutscher Sprache oder in zwei Sprachen eingesetzt werden: 
Error: DM01AVTG24LV95.Bodenbedeckung.BBNachfuehrung.Perimeter: tid 1657680: superfluous outerboundary tid 1657680   oder / überflüssig Perimeter Grenze

4.	Die Struktur des Logfiles kann gegliedert werden (Topic; Classe....) anstatt "info:"

5.	getrennte Logdateien für statistische Ausgabe (Fehlerstatistik)

6.	Einzelne Modellverschärfungen und zusätzliche Prüfmethoden [GeoW_FunctionsExt](https://github.com/GeoWerkstatt/geow-interlis-functions/blob/master/src/model/GeoW_FunctionsExt.ili)  sind noch einzeln hinzuzufügen, die Frage ist, ob die CH-Fehler auch einzeln hinzugefügt werden sollen oder ob sie ebenfalls automatisch aufgenommen werden sollen, Kanton unabhängig
7.	Eine XML-Datei oder XLS mit einem Ili-Modell wird nicht erkannt Z.B.: 
<?xml version="1.0" encoding="UTF-8"?>
[<ThurgisQualityClassTG>](file:///S:/Daten/abfa/1/ilicop/bade/Limsophy_Prod_20220817_BWN_aktuellste_QualKlassen.xml)[<Probenstelle>](file:///S:/Daten/abfa/1/ilicop/bade/Limsophy_Prod_20220817_BWN_aktuellste_QualKlassen.xml)<PSID>2481</PSID><ProbenNr>310220</ProbenNr><Erhebungsdatum>2022-08-15</Erhebungsdatum><QualKlasse>A</QualKlasse></Probenstelle>[<Probenstelle>](file:///S:/Daten/abfa/1/ilicop/bade/Limsophy_Prod_20220817_BWN_aktuellste_QualKlassen.xml)<PSID>2483</PSID><ProbenNr>310219</ProbenNr><Erhebungsdatum>2022-08-15</Erhebungsdatum><QualKlasse>A</QualKlasse></Probenstelle>[<Probenstelle>](file:///S:/Daten/abfa/1/ilicop/bade/Limsophy_Prod_20220817_BWN_aktuellste_QualKlassen.xml)<PSID>8271</PSID><ProbenNr>310225</ProbenNr><Erhebungsdatum>2022-08-15</Erhebungsdatum><QualKlasse>A</QualKlasse></Probenstelle>[<Probenstelle>](file:///S:/Daten/abfa/1/ilicop/bade/Limsophy_Prod_20220817_BWN_aktuellste_QualKlassen.xml)
……
Wird als  Error: unknown xml file / so wie csv Dateien 

8.	Der XTF-Log-Checker ist nur nützlich, wenn Koordinaten verfügbar sind. Meistens ist eine Liste mit BID TID ohne Koordinaten.  Die Antwort ist immer eine XTF-Datei, unabhängig vom Dateiformat (itf; XML ...)
9.	Die Log-Datei basiert auf ILI2. D.h. der Vergleich einer ITF-Datei ("ILI1") mit einer Log-Datei ("ILI2") ist zwar möglich, aber nicht durchführbar.

Modell Modellinformationen sind vorhanden; der Name der Imputdatei ist nur im Namen der Log-Datei enthalten und nicht innerhalb der Log-Datei.{
  "jobId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "statusUrl": "string"
}

 Job ID Info: lookup model <DM01AVTG24LV95> 1.0 in repository </uploads/091c2d29-4d31-4999-b4fa-a93695ba2997/>
Info: ilifile </uploads/091c2d29-4d31-4999-b4fa-a93695ba2997/yh3nudf4.ili>
Info: validate data...
Danke und Gruss
Maud

**Comment by Philippluca** [comment]
Feedback issue. Feedback betrifft Funktionalität von https://github.com/claeis/ilivalidator.
