### ISSUE TITLE
Feedback zu Beta Version

### ISSUE THREAD

**Issue by nrohrbach** [GeoWerkstatt/interlis-check-service#125]
Hallo zäme

Vielen Dank für die super Umsetzung dieses Dienstes.
Ich habe die verschiedenen Endpoints mit FME getestet.
Folgende Dinge habe ich getestet:

**Upload**

- Upload Xtf-File
- Upload Gpgk-File
- Upload Zip-File
- Upload Itf-File
- Upload Xml-File
- UploadResponse ist gemäss Dokumentation
- HTTP Code 201 erscheint bei erfolgreichem Upload
- HTTP Code 400 erscheint bei Fehlern in der Anfrage
- HTTP Code 413 erscheint NICHT bei zu grossen Files. Es erscheint ein 400er.
- Der Endpoint hat Probleme mit Umlauten im Dateipfad z.B. _D:\ilicop\sül\test.xtf_

**Comment by nrohrbach** [comment]
**Status**

- Erfolgreiche Antwort "processing" erhalten
- Erfolgreiche Antwort "completed" erhalten
- Erfolgreiche Antwort "completedWithErrors" erhalten
- HTTP Code 200 erscheint bei erfolgreichem Aufruf
- HTTP Code 400 erscheint bei fehlerhafter Anfrage
- HTTP Code 404 erscheint bei nicht vorhandener JobId
- Response bei 400er und 404er entspricht nicht der Doku und sieht wie folgt aus:

`
{
	"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
	"title": "One or more validation errors occurred.",
	"status": 400,
	"traceId": "00-9bf77aea278f151cc463427b3be89fdc-67208ff29da2f6c5-00",
	"errors": {
		"jobId": ["The value '31b0bbf0-0bb1-4275-b9c6-7f2ada60d2c6sdw' is not valid."]
	}
}
`

**Comment by nrohrbach** [comment]
**Download**

- Erfolgreiche Abfrage Logfile mit logType=log
- Erfolgreiche Abfrage Logfile mit logType=xtf
- HTTP Code 200 erscheint bei erfolgreichem Aufruf. In der Doku steht HTTP Code 201
- HTTP Code 400 erscheint bei fehlerhaftem Aufruf.
- HTTP Code 404 erscheint bei JobId für welche kein Job vorhanden ist.
-

**Comment by nrohrbach** [comment]
**Settings**

- Erfolgreicher Aufruf der Settings
-  Die Antwort entspricht der Dokumentation

**Comment by olivergrimm** [comment]
Update:

- Upload: Problem mit Umlauten konnte auf FME Version zurückgeführt werden (<2021.1) .
- Status: Doku und Response wird harmonisiert
