### ISSUE TITLE
Allow upload of multiple xtf files

### ISSUE THREAD

**Issue by cjenal** [GeoWerkstatt/interlis-check-service#152]
The INTERLIS model http://models.geo.admin.ch/BLW/LWB_Nutzungsflaechen_V2_0.ili has an association to an external model. To validate the xtf I would need to upload the xtf according to the model LWB_Nutzungsflaechen_V2_0.ili as well as the xtf according to the referenced model LWB_Bewirtschaftungseinheiten_V2_0.ili. 
Why is it not possible to upload 2 (or more) xtf files to validate external references?

**Comment by Philippluca** [comment]
Currently we have no way of knowing which xtf file must be validated first, therefore multiple xtf files are not supported.
However, if you need to validate one xtf which has external dependencies you can try to add/handle it as a catalog file by renaming it with the .xml extension. You can put the xtf and all corresponding catalog files (.xml) in one ZIP and validate them in one go.

**Comment by flenny** [comment]
Hi @cjenal, Please let us know if the validation with renamed catalog files worked as expected. Regards Oliver

**Comment by cjenal** [comment]
@flenny Yes, the validation worked with renaming the second xtf files to .xml. Maybe you should add this in the help section. Thank you!
