### ISSUE TITLE
ili2db als zusätzlicher Backend-Service einbinden

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-check-service#177]
Das ilicop-Backend soll so erweitert werden, dass ili2db als Service zur Verfügung steht.
Einbindung, Konfiguration analog ilivalidator

Schalter um GPKG-Validierung zu aktivieren integrieren

**Comment by Philippluca** [comment]
Resolved by https://github.com/GeoWerkstatt/interlis-check-service/pull/69
