### ISSUE TITLE
Adding additional VSA organisations does not work

### ISSUE THREAD

**Issue by sjib** [GeoWerkstatt/interlis-check-service#193]
If I test the current VSA-DSS 2020 Testdatensatz I get the following errors:

![20240408_ilicop_tests_transferdatensatz_2020](https://github.com/GeoWerkstatt/interlis-check-service/assets/1265865/ba62029f-0a31-4209-abf9-0e6809d8f2e8)

Missing organisation reference.
If I then want to add those and upload them as a zip, I get the following error:
![20240408_ilicop_tests_inkl_extra_organisationen](https://github.com/GeoWerkstatt/interlis-check-service/assets/1265865/96011bdc-4665-42ff-9f16-3d4a288d41eb)

So it is great that the VSA organisation dataset is found in the VSA repo, but if there are missing organisations that I maybe maintain locally I cannot add them with the data. It would be great if I could upload those with the other data.

**Comment by sjib** [comment]
![20240408_ilicop_nur_eine_datei_error](https://github.com/GeoWerkstatt/interlis-check-service/assets/1265865/d809cf59-98d8-44d3-bd25-4dbd5b86ac14)

**Comment by sjib** [comment]
@beistehen Umbenennen einer Datei auf xml gibt gleiche Fehlermeldung.

**Comment by sjib** [comment]
Man könnte ja wie im GUI die Reihenfolge definieren. 
Im Moment ist es komisch, dass die zweitgewählte Datei in der Reihenfolge zuerst kommmt - das sollte umgekehrt sein finde ich um logisch zu sein.
![20240408_ilicop_nur_eine_datei_error_zwei_files_reihenfolge](https://github.com/GeoWerkstatt/interlis-check-service/assets/1265865/80f39677-c712-44d4-a961-b823025cecdd)

**Comment by olivergrimm** [comment]
@sjib Du kannst die Dateien in einer ZIP-Datei hochladen. ilicop entzippt diese anschliessend und validiert das XTF unter Berücksichtigung aller zusätzlich mitgelieferter XMLs.

**Comment by sjib** [comment]
![20240408_ilicop_xtf_xml_gezippt_ok](https://github.com/GeoWerkstatt/interlis-check-service/assets/1265865/895acc89-abbd-4934-8eb7-59fba67cce68)

So geht es: 

- xtf mit GEP Daten,
- xml mit zusätzlichen Organisationen 
- und gezippt hochladen!

**Comment by sjib** [comment]
@olivergrimm 

- Die VSA Organisationen scheint er schon jetzt zu kennen: www.vsa.ch/models/organisation - das ist das was ich am Anfang schon gesehen habe
- Nur mit den zusätzlichen Organisationen ging es am Anfang nicht - aber ihr seht ja jetzt, wie ihr eure Doku ergänzen könnt.
- Wo ist die online?

**Comment by Philippluca** [comment]
Replaced by #209
