### ISSUE TITLE
Ergänzung der Anzahl Fehler

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-check-service#201]
Feedback von C. Jenal zur erweiterten Fehlerausgabe:
Es wäre schön, wenn die Anzahl Fehler summiert werden und ein Total angezeigt wird und pro Fehlermeldung auch anzeigen, wie oft dieser Fehler auftritt. 
 
![image](https://github.com/GeoWerkstatt/interlis-check-service/assets/3465512/a2ff5b80-4165-4238-938f-7cb23bf8775c)

(Wert 99.00 kommt in über 80 Fällen vor in den Attributen RBHL, RB und RBUS)

**Comment by beistehen** [comment]
Zu #201 (diesem Issue), #202 und #203 siehe auch Bestrebungen unter
* https://github.com/claeis/ilivalidator/issues/34 (closed, jedoch nicht komplett umgesetzt)
* https://github.com/claeis/ilivalidator/issues/362#issuecomment-1294549276 (Meinung Claude)
* https://github.com/claeis/ilivalidator/issues/254 (Vergabe von Fehlernummern)

**Comment by Philippluca** [comment]
Clased as Inputs have been moved to discussion: https://github.com/GeoWerkstatt/geopilot/discussions/330
