### ISSUE TITLE
Gruppierung gleicher Fehler

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-check-service#202]
Feedback von C.Jenal zur erweiterten Fehlerausgabe:
Die Fehlermeldungen werden ja gruppiert, aber wenn die Anzahl der Beziehungen nicht gleich ist, wird dieselbe Fehlermeldung mehrmals ausgegeben (siehe gelb markierte Meldungen unten). Konsequenterweise müssten die m.E. auch zusammengefasst werden. 

![image](https://github.com/GeoWerkstatt/interlis-check-service/assets/3465512/1d0f1616-0335-44d5-bd7f-b178f4e62c27)

**Comment by Philippluca** [comment]
Clased as Inputs have been moved to discussion: https://github.com/GeoWerkstatt/geopilot/discussions/330
