### ISSUE TITLE
Aufbau der Logmeldung optimieren

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-check-service#203]
Feedback von C.Jenal zur erweiterten Logausgabe:
Zudem würde ich mir wünschen, dass wie im LogFile der Klassenname am Anfang der Zeile steht, damit man weiss in welcher Klasse der Fehler auftritt. Ich habe in diesem geprüften Modell zwei Beziehungen mit gleicher Rolle. Einmal ist es eine 1..*- Beziehung, einmal eine 1..1-Beziehung (siehe blaue Markierungen). Da die Rolle gleich heisst, weiss ich so nicht gleich in welcher Klasse der Fehler liegt ohne auf die Kardinalität zu achten. Ohne den entsprechenden Klassennamen kommt man doch nicht darum herum im LogFile nachzuschauen. 
![image](https://github.com/GeoWerkstatt/interlis-check-service/assets/3465512/ffcdc747-cd07-4b50-916e-0d0dcf89f04b)

**Comment by Philippluca** [comment]
Clased as Inputs have been moved to discussion: https://github.com/GeoWerkstatt/geopilot/discussions/330
