### ISSUE TITLE
Zuordnung der Fehler nach Klasse 

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-check-service#204]
Feedback von C.Jenal zur erweiterten Logausgabe:
Gemäss deinem Eintrag im Interlis-Forum dachte ich, dass die Fehler nach Klasse zugeordnet werden. Bei meinen zwei Beispielen erscheinen aber alle Fehler unter «Weitere Meldungen».

**Comment by Philippluca** [comment]
Clased as Inputs have been moved to discussion: https://github.com/GeoWerkstatt/geopilot/discussions/330
