### ISSUE TITLE
Geojson: Erweiterung der TID

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-check-service#205]
Feedback von C.Jenal zur erweiterten Logausgabe:
Das GeoJson finde ich aber super. Dort sind alle relevanten Informationen drin und lokalisiert. Einzig die Ergänzung der xtf_id würde ich mir noch wünschen. Die Info zu «Zeilennummer» finde ich nicht nützlich zumal diese ja nicht unbedingt gleich bleibt, wenn man z.B. im Editor den Zeilenumbruch einschaltet zur besseren Lesbarkeit.

**Comment by Philippluca** [comment]
Clased as Inputs have been moved to discussion: https://github.com/GeoWerkstatt/geopilot/discussions/330
