### ISSUE TITLE
Feature Request: Provide own model(s)

### ISSUE THREAD

**Issue by beistehen** [GeoWerkstatt/interlis-check-service#73]
Nicht alle Modelle sind in Repositories verfügbar. Ich fände es nützlich, wenn man bei Bedarf nebst dem .xtf auch 1 oder mehrere Modelle hochladen könnte, welche dann für die Prüfung verwendet werden.

**Comment by olivergrimm** [comment]
Danke für den Request. Aktuell können beliebige Repositories serverseitig konfiguriert werden, dies ermöglicht, dass der Validator neben den öffentlichen auch private oder lokale Repositories konsumiert. Diese Konfiguration bietet sich bei dedizierten Mandanten an und wird dort auch erfolgreich angewendet.
Ein Upload einer, oder im Falle weiterer Abhängigkeiten auch mehrerer Modelle, wäre technisch möglich. In die gleiche Enhancement Kategorie fällt auch der INTERLIS 1 Support sowie der Support lokaler Kataloge. Aktuell können wir nicht genau abschätzen, wie hoch der Bedarf dafür ist und wer alles daran interessiert ist.

**Comment by olivergrimm** [comment]
@beistehen Das Feature wurde released.
